<? $title = '订单'; ?>
<? include 'head.phtml'; ?>

    <div class="container">
      <div class="m_index_main">
        <div class="weui_panel weui_panel_access">
          <div class="weui_panel_bd">
          	<? for ($i = 0; $i < 5; $i++ ): ?>
          		<? if ($i == 3): ?>
          			
          		<? endif; ?>
          	<? endfor; ?>
            <div class="m_card">
              <a href="javascript:void(0);" class="weui_media_box weui_media_appmsg m_card_top">
                <div class="weui_media_hd">
                  <img class="weui_media_appmsg_thumb br50" src="../img/69logo_150.jpg" alt="">
                </div>
                <div class="weui_media_bd">
                  <h4 class="weui_media_title" id="u_id">
                    <span class="pr10">标题一</span>
                    <img src="../img/10.png" class="pr5" />
                    <img src="../img/10.png" class="pr5" />
                  </h4>
                  <p class="weui_media_desc">
                    <span class="pr10">一小时前</span>
                    <span>上海市徐汇区</span>
                  </p>
                </div>
              </a>
              <div class="m_card_main">
                <div class="rel">
                  <img src="../img/welcome_69.jpg" class="m_card_main_img" />
                  <div class="m_card_main_img_num">共<span>5</span>张</div>
                </div>
                <p class="m_card_main_text">
					由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。
                </p>
              </div>
              <div class="m_card_bottom">
                <a href="javascript:void(0);" class="weui_media_box weui_media_appmsg m_card_hotel_info">
                  <div class="weui_media_hd">
                    <img class="weui_media_appmsg_thumb" src="../img/69logo_150.jpg" alt="">
                  </div>
                  <div class="weui_media_bd">
                    <h4 class="weui_media_title hotel_name" id="hotel_name">卓美亚托尼大酒店</h4>
                    <p class="weui_media_desc">
                      <span class="">本次评分</span>
                      <span class="">3.0</span>
                    </p>
                  </div>
                  <div class="m_card_arrow_right">
                    <img src="../img/arrow_right_black@2x.png" />
                  </div>
                </a>
                <div class="m_card_function">
                  <div class="m_card_function_left l">
                    <span class="m_card_function_zan">
                      <img src="../img/zan_hover@2x.png" />123
                    </span>
                    <span class="m_card_function_comment">
                      <img src="../img/comment_hover@2x.png" />325
                    </span>
                  </div>
                  <div class="m_card_function_right r">
                    <button>可约</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="m_card">
              <a href="javascript:void(0);" class="weui_media_box weui_media_appmsg m_card_top">
                <div class="weui_media_hd">
                  <img class="weui_media_appmsg_thumb br50" src="../img/69logo_150.jpg" alt="">
                </div>
                <div class="weui_media_bd">
                  <h4 class="weui_media_title" id="u_id">
                    <span class="pr10">标题一</span>
                    <img src="../img/10.png" class="pr5" />
                    <img src="../img/10.png" class="pr5" />
                  </h4>
                  <p class="weui_media_desc">
                    <span class="pr10">一小时前</span>
                    <span>上海市徐汇区</span>
                  </p>
                </div>
              </a>
              <div class="m_card_main">
                <div>
                  <img src="../img/welcome_69.jpg" class="m_card_main_img" />
                </div>
                <p class="m_card_main_text">
				  由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。
                </p>
              </div>
              <div class="m_card_bottom">
                <a href="javascript:void(0);" class="weui_media_box weui_media_appmsg m_card_hotel_info">
                  <div class="weui_media_hd">
                    <img class="weui_media_appmsg_thumb" src="../img/69logo_150.jpg" alt="">
                  </div>
                  <div class="weui_media_bd">
                    <h4 class="weui_media_title hotel_name" id="hotel_name">卓美亚托尼大酒店</h4>
                    <p class="weui_media_desc">
                      <span class="">本次评分</span>
                      <span class="">3.0</span>
                    </p>
                  </div>
                  <div class="m_card_arrow_right">
                    <img src="../img/arrow_right_black@2x.png" />
                  </div>
                </a>
                <div class="m_card_function">
                  <div class="m_card_function_left l">
                    <span class="m_card_function_zan">
                      <img src="../img/zan_hover@2x.png" />123
                    </span>
                    <span class="m_card_function_comment">
                      <img src="../img/comment_hover@2x.png" />325
                    </span>
                  </div>
                  <div class="m_card_function_right r">
                    <button>可约</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="m_nearby">
              <img src="../img/m_nearby.jpg" />
              <div class="m_local_icon">
                <i class="m_circle">
                </i>
                <span class="m_local_rect">上海市徐汇区</span>
              </div>
              <div class="btn_nearby">
                <span class="btn_nearby_text">点击查看附近的人</span>
              </div>
            </div>
            <div class="m_operation">
              <img src="../img/welcome_69.jpg" />
              <div class="m_operation_bottom">
                <div class="m_operation_title">为什么元宵节要吃汤圆?</div>
                <div class="m_operation_contant">吃汤圆吃汤圆吃汤圆吃汤圆吃汤圆吃汤圆吃汤圆吃汤圆吃汤圆吃汤圆</div>
              </div>
            </div>
            <div class="m_card">
              <a href="javascript:void(0);" class="weui_media_box weui_media_appmsg m_card_top">
                <div class="weui_media_hd">
                  <img class="weui_media_appmsg_thumb br50" src="../img/69logo_150.jpg" alt="">
                </div>
                <div class="weui_media_bd">
                  <h4 class="weui_media_title" id="u_id">
                    <span class="pr10">标题一</span>
                    <img src="../img/10.png" class="pr5" />
                    <img src="../img/10.png" class="pr5" />
                  </h4>
                  <p class="weui_media_desc">
                    <span class="pr10">一小时前</span>
                    <span>上海市徐汇区</span>
                  </p>
                </div>
              </a>
              <div class="m_card_main">
                <div>
                  <img src="../img/welcome_69.jpg" class="m_card_main_img" />
                </div>
                <p class="m_card_main_text">
					由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。由各种物质组成的巨型球状天体，叫做星球。星球有一定的形状，有自己的运行轨道。
                </p>
              </div>
              <div class="m_card_bottom">
                <a href="javascript:void(0);" class="weui_media_box weui_media_appmsg m_card_hotel_info">
                  <div class="weui_media_hd">
                    <img class="weui_media_appmsg_thumb" src="../img/69logo_150.jpg" alt="">
                  </div>
                  <div class="weui_media_bd">
                    <h4 class="weui_media_title hotel_name" id="hotel_name">卓美亚托尼大酒店</h4>
                    <p class="weui_media_desc">
                      <span class="">本次评分</span>
                      <span class="">3.0</span>
                    </p>
                  </div>
                  <div class="m_card_arrow_right">
                    <img src="../img/arrow_right_black@2x.png" />
                  </div>
                </a>
                <div class="m_card_function">
                  <div class="m_card_function_left l">
                    <span class="m_card_function_zan">
                      <img src="../img/zan_hover@2x.png" />123
                    </span>
                    <span class="m_card_function_comment">
                      <img src="../img/comment_hover@2x.png" />325
                    </span>
                  </div>
                  <div class="m_card_function_right r">
                    <button>可约</button>
                </div>
              </div>
            </div>
          </div>
          </div>
        </div>
	  </div>
      <div class="m_fixed_bottom">
      	<div class="m_fiexd_bottom_tabs">
	      	<div class="m_selected m_col_50" id="m_newest">
	          	最新
	        </div>
	        <div class="m_col_50" id="m_recommend">
	          	推荐
	        </div>
	        <div class="m_search" id="m_index_bottom_search">
	          <img src="../img/i-search@2x.png" />
	        </div>
        </div>
      	<div class="weui_search_bar" id="search_bar">
	      <form class="weui_search_outer">
	        <div class="weui_search_inner">
	          <i class="weui_icon_search">
	          </i>
	          <input type="search" class="weui_search_input" id="search_input" placeholder="搜索"
	          required/>
	          <a href="javascript:" class="weui_icon_clear" id="search_clear">
	          </a>
	        </div>	        
	      </form>
	    </div>
      </div>
    </div>

    <script>
    	$(function(){
    		$(document).on("click", "#m_index_bottom_search", function(e) {
			    $(e.target).parents(".m_fixed_bottom").addClass("weui_search_focusing");
			  }) 
			  .on("blur", ".weui_search_input", function(e) {
			    var $input = $(e.target);
			    if(!$input.val()) $input.parents(".m_fixed_bottom").removeClass("weui_search_focusing");
			  })
			  .on("click", ".weui_icon_clear", function(e) {
			    var $input = $(e.target).parents(".weui_search_bar").find(".weui_search_input").val("").focus();
			  });
    	})
    	
    </script>
  </body>
</html>